version: '3.11'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-2cvm(=toy6z!i#%76fq2fiw*99=4v&a^-tv#528*+tx3r8+sp@"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
  
